In [13]:

from operator import index

import pandas as pd
from numpy.conftest import dtype

In [1]:
s = pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])

NameError: name 'pd' is not defined

In [20]:
class Names:
    pass
class marks:
    pass


d= pd.DataFrame({Names: ["janvi","chetna","vaish"], marks:[1,2,3]})

In [21]:
d

  <class '__main__.Names'>  <class '__main__.marks'>
0                    janvi                         1
1                   chetna                         2
2                    vaish                         3

In [16]:
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [22]:
s.describe()

count    5.000000
mean     3.000000
std      1.581139
min      1.000000
25%      2.000000
50%      3.000000
75%      4.000000
max      5.000000
dtype: float64

In [30]:
d.rename(columns={"Names":"MRRR"})

  <class '__main__.Names'>  <class '__main__.marks'>
0                    janvi                         1
1                   chetna                         2
2                    vaish                         3

In [31]:
d.columns

Index([<class '__main__.Names'>, <class '__main__.marks'>], dtype='object')

In [32]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   <class '__main__.Names'>  3 non-null      object
 1   <class '__main__.marks'>  3 non-null      int64
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes

In [35]:
s.info()

<class 'pandas.core.series.Series'>
Index: 5 entries, a to e
Series name: None
Non-Null Count  Dtype
--------------  -----
5 non-null      int64
dtypes: int64(1)
memory usage: 80.0+ bytes

In [36]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   <class '__main__.Names'>  3 non-null      object
 1   <class '__main__.marks'>  3 non-null      int64
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes

In [45]:
d.columns

Index(['Names', 'marks'], dtype='object')

In [42]:
d.columns=['Names','marks']

In [49]:
d.rename(columns={'MRRR':'Names'})

    Names  marks
0   janvi    1.0
1  chetna    2.0
2   vaish    3.0

In [50]:
d['marks']=d['marks'].astype(float)

In [51]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Names   3 non-null      object
 1   marks   3 non-null      float64
dtypes: float64(1), object(1)
memory usage: 180.0+ bytes